[package]
name = "discord_bot"
version = "0.2.0"
authors = ["midori"]

[dependencies]
serenity = "0.5"
curl="0.4.18"
serde_json="1.0"
reqwest="0.9.12"
rand="0.6.5"

[patch.crates-io]
openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }
